version: '3.7'

networks:
  go-postgres13-network:

services:
  go-web-service:
    build:
      context: .
    container_name: go-web-app
    ports:
      - "80:8080"
    volumes:
      - ./app:/app
    command: sh -c "go build -o /app_build/main . && /app_build/main" # "main" - app name
    depends_on:
      - postgres13-service


  # postgres
  postgres13-service:
    image: postgres:13-alpine
    container_name: postgres13-container
    ports:
      - "5434:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always # always restart unless stopped manually
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    networks:
      - go-postgres13-network